"""
Model Interpretation Utilities
==============================

Reusable utilities for interpreting the two-head protein corona model.

This module supports two major analyses:

1. Abundance-head interpretation
   - Protein-specific Pearson correlation.
   - Ranking proteins by training abundance.
   - High / Middle / Low abundance tertiles.
   - Tertile-level performance summaries.

2. Adsorption-head SHAP interpretation
   - Standardizing SHAP output arrays.
   - Calculating mean absolute SHAP values.
   - Expressing feature importance relative to the maximum.
   - Preparing feature x protein tables for heatmaps.

Plotting is intentionally NOT performed here.

Publication figures should later be generated by a dedicated script or
plotting module.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping, Optional, Sequence

import numpy as np
import pandas as pd

from pcmodel.metrics import (
    per_protein_pearson,
)


# ======================================================================
# Constants
# ======================================================================

ABUNDANCE_TERTILE_ORDER = [
    "High",
    "Middle",
    "Low",
]


# ======================================================================
# Abundance interpretation result
# ======================================================================


@dataclass
class AbundanceInterpretationResult:
    """
    Protein-level abundance interpretation results.
    """

    protein_table: pd.DataFrame

    tertile_summary: pd.DataFrame


# ======================================================================
# Input validation
# ======================================================================


def _validate_2d_same_shape(
    observed: np.ndarray,
    predicted: np.ndarray,
) -> None:
    """
    Validate two matching two-dimensional matrices.
    """

    observed = np.asarray(
        observed
    )

    predicted = np.asarray(
        predicted
    )

    if (
        observed.ndim != 2
        or predicted.ndim != 2
    ):

        raise ValueError(
            "Observed and predicted abundance arrays "
            "must both be 2-dimensional."
        )

    if (
        observed.shape
        != predicted.shape
    ):

        raise ValueError(
            "Observed and predicted matrices must have "
            "identical shape. "
            f"Received {observed.shape} and "
            f"{predicted.shape}."
        )


# ======================================================================
# Training abundance ranking
# ======================================================================


def mean_training_abundance(
    training_abundance: np.ndarray,
) -> np.ndarray:
    """
    Calculate mean training abundance for each protein.
    """

    training_abundance = np.asarray(
        training_abundance,
        dtype=float,
    )

    if (
        training_abundance.ndim
        != 2
    ):

        raise ValueError(
            "training_abundance must be a 2D array."
        )

    return np.mean(
        training_abundance,
        axis=0,
    )


def assign_abundance_tertiles(
    training_abundance: np.ndarray,
    protein_ids: Sequence[str],
) -> pd.DataFrame:
    """
    Rank proteins by mean abundance in the model-development set
    and assign them to High, Middle, and Low abundance tertiles.

    Proteins are sorted from highest to lowest mean abundance and
    divided into three approximately equal-sized groups.

    Parameters
    ----------
    training_abundance
        Shape:
            n_training_samples x n_proteins

    protein_ids
        Protein identifiers corresponding to the abundance columns.

    Returns
    -------
    pandas.DataFrame
        Columns:
            protein
            mean_training_abundance
            abundance_rank
            abundance_tertile
    """

    training_abundance = np.asarray(
        training_abundance,
        dtype=float,
    )

    protein_ids = list(
        protein_ids
    )

    if (
        training_abundance.shape[1]
        != len(
            protein_ids
        )
    ):

        raise ValueError(
            "Number of protein IDs does not match "
            "training abundance matrix width."
        )

    means = mean_training_abundance(
        training_abundance
    )

    # --------------------------------------------------------------
    # Sort from highest to lowest abundance.
    # mergesort provides deterministic handling of ties.
    # --------------------------------------------------------------

    sorted_indices = np.argsort(
        -means,
        kind="mergesort",
    )

    # --------------------------------------------------------------
    # Divide the ranked proteins into three nearly equal groups.
    # --------------------------------------------------------------

    split_indices = np.array_split(
        sorted_indices,
        3,
    )

    tertile_labels = np.empty(
        len(
            protein_ids
        ),
        dtype=object,
    )

    for label, indices in zip(
        ABUNDANCE_TERTILE_ORDER,
        split_indices,
    ):

        tertile_labels[
            indices
        ] = label

    # --------------------------------------------------------------
    # Rank numbers
    # --------------------------------------------------------------

    ranks = np.empty(
        len(
            protein_ids
        ),
        dtype=int,
    )

    for rank, index in enumerate(
        sorted_indices,
        start=1,
    ):

        ranks[
            index
        ] = rank

    table = pd.DataFrame(
        {
            "protein":
                protein_ids,

            "mean_training_abundance":
                means,

            "abundance_rank":
                ranks,

            "abundance_tertile":
                tertile_labels,
        }
    )

    return table.sort_values(
        "abundance_rank"
    ).reset_index(
        drop=True
    )


# ======================================================================
# Protein-level abundance interpretation
# ======================================================================


def build_abundance_protein_table(
    observed_abundance: np.ndarray,
    predicted_abundance: np.ndarray,
    training_abundance: np.ndarray,
    protein_ids: Sequence[str],
    *,
    id_to_name: Optional[
        Mapping[str, str]
    ] = None,
    id_to_category: Optional[
        Mapping[str, str]
    ] = None,
) -> pd.DataFrame:
    """
    Build a protein-level abundance interpretation table.

    The table combines:
    - training abundance
    - abundance rank
    - abundance tertile
    - Pearson correlation on the held-out test set
    - optional protein names
    - optional functional categories
    """

    _validate_2d_same_shape(
        observed_abundance,
        predicted_abundance,
    )

    protein_ids = list(
        protein_ids
    )

    if (
        observed_abundance.shape[1]
        != len(
            protein_ids
        )
    ):

        raise ValueError(
            "Number of protein IDs does not match "
            "observed/predicted matrix width."
        )

    if (
        training_abundance.shape[1]
        != len(
            protein_ids
        )
    ):

        raise ValueError(
            "Number of protein IDs does not match "
            "training abundance matrix width."
        )

    # --------------------------------------------------------------
    # Protein-specific Pearson correlation
    # --------------------------------------------------------------

    correlations = (
        per_protein_pearson(
            observed_abundance,
            predicted_abundance,
        )
    )

    # --------------------------------------------------------------
    # Abundance tertiles
    # --------------------------------------------------------------

    table = (
        assign_abundance_tertiles(
            training_abundance,
            protein_ids,
        )
    )

    correlation_map = dict(
        zip(
            protein_ids,
            correlations,
        )
    )

    table[
        "pearson_r"
    ] = table[
        "protein"
    ].map(
        correlation_map
    )

    # --------------------------------------------------------------
    # Observed and predicted mean abundance
    # --------------------------------------------------------------

    observed_mean = np.mean(
        observed_abundance,
        axis=0,
    )

    predicted_mean = np.mean(
        predicted_abundance,
        axis=0,
    )

    observed_map = dict(
        zip(
            protein_ids,
            observed_mean,
        )
    )

    predicted_map = dict(
        zip(
            protein_ids,
            predicted_mean,
        )
    )

    table[
        "mean_test_observed"
    ] = table[
        "protein"
    ].map(
        observed_map
    )

    table[
        "mean_test_predicted"
    ] = table[
        "protein"
    ].map(
        predicted_map
    )

    # --------------------------------------------------------------
    # Protein names
    # --------------------------------------------------------------

    if (
        id_to_name
        is not None
    ):

        table[
            "protein_name"
        ] = table[
            "protein"
        ].map(
            id_to_name
        ).fillna(
            "<UNKNOWN>"
        )

    # --------------------------------------------------------------
    # Functional categories
    # --------------------------------------------------------------

    if (
        id_to_category
        is not None
    ):

        table[
            "category"
        ] = table[
            "protein"
        ].map(
            id_to_category
        ).fillna(
            "Other/Mixed"
        )

    return table


# ======================================================================
# Abundance tertile summary
# ======================================================================


def summarize_abundance_tertiles(
    protein_table: pd.DataFrame,
) -> pd.DataFrame:
    """
    Summarize protein-specific Pearson correlations by abundance tertile.

    Returns:
        N proteins
        N valid correlations
        median Pearson r
        Q1
        Q3
        IQR
        minimum
        maximum
    """

    required = {
        "abundance_tertile",
        "pearson_r",
    }

    missing = (
        required
        - set(
            protein_table.columns
        )
    )

    if missing:

        raise ValueError(
            "Protein table is missing required columns: "
            f"{sorted(missing)}"
        )

    rows = []

    for tertile in (
        ABUNDANCE_TERTILE_ORDER
    ):

        subset = protein_table[
            protein_table[
                "abundance_tertile"
            ]
            == tertile
        ]

        correlations = (
            subset[
                "pearson_r"
            ]
            .dropna()
            .to_numpy(
                dtype=float
            )
        )

        if (
            len(correlations)
            > 0
        ):

            q1 = float(
                np.percentile(
                    correlations,
                    25,
                )
            )

            median = float(
                np.median(
                    correlations
                )
            )

            q3 = float(
                np.percentile(
                    correlations,
                    75,
                )
            )

            minimum = float(
                np.min(
                    correlations
                )
            )

            maximum = float(
                np.max(
                    correlations
                )
            )

        else:

            q1 = np.nan
            median = np.nan
            q3 = np.nan
            minimum = np.nan
            maximum = np.nan

        rows.append(
            {
                "Abundance_tertile":
                    tertile,

                "N_proteins":
                    int(
                        len(
                            subset
                        )
                    ),

                "N_valid_r":
                    int(
                        len(
                            correlations
                        )
                    ),

                "Median_r":
                    median,

                "Q1":
                    q1,

                "Q3":
                    q3,

                "IQR":
                    (
                        q3 - q1
                        if (
                            np.isfinite(
                                q1
                            )
                            and np.isfinite(
                                q3
                            )
                        )
                        else np.nan
                    ),

                "Min_r":
                    minimum,

                "Max_r":
                    maximum,
            }
        )

    return pd.DataFrame(
        rows
    )


# ======================================================================
# Full abundance interpretation workflow
# ======================================================================


def abundance_interpretation(
    observed_abundance: np.ndarray,
    predicted_abundance: np.ndarray,
    training_abundance: np.ndarray,
    protein_ids: Sequence[str],
    *,
    id_to_name: Optional[
        Mapping[str, str]
    ] = None,
    id_to_category: Optional[
        Mapping[str, str]
    ] = None,
) -> AbundanceInterpretationResult:
    """
    Run the complete abundance-head interpretation calculation.
    """

    protein_table = (
        build_abundance_protein_table(
            observed_abundance,
            predicted_abundance,
            training_abundance,
            protein_ids,
            id_to_name=id_to_name,
            id_to_category=(
                id_to_category
            ),
        )
    )

    tertile_summary = (
        summarize_abundance_tertiles(
            protein_table
        )
    )

    return (
        AbundanceInterpretationResult(
            protein_table=(
                protein_table
            ),
            tertile_summary=(
                tertile_summary
            ),
        )
    )


# ======================================================================
# SHAP utilities
# ======================================================================


def standardize_shap_array(
    shap_values,
) -> np.ndarray:
    """
    Convert common SHAP output formats into:

        n_samples x n_features x n_outputs

    Supported inputs
    ----------------
    1. NumPy array:
           samples x features

    2. NumPy array:
           samples x features x outputs

    3. List of arrays:
           one samples x features array per output

    This function does NOT calculate SHAP values.
    It standardizes values produced by a SHAP explainer.
    """

    # --------------------------------------------------------------
    # Old SHAP API:
    # list with one matrix per model output.
    # --------------------------------------------------------------

    if isinstance(
        shap_values,
        list,
    ):

        arrays = [
            np.asarray(
                value,
                dtype=float,
            )
            for value
            in shap_values
        ]

        if not arrays:

            raise ValueError(
                "SHAP list is empty."
            )

        first_shape = (
            arrays[
                0
            ].shape
        )

        if any(
            value.shape
            != first_shape
            for value
            in arrays
        ):

            raise ValueError(
                "SHAP output arrays have inconsistent shapes."
            )

        if (
            len(
                first_shape
            )
            != 2
        ):

            raise ValueError(
                "List-based SHAP values must contain "
                "2D sample x feature arrays."
            )

        return np.stack(
            arrays,
            axis=2,
        )

    # --------------------------------------------------------------
    # Newer SHAP API or standard ndarray.
    # --------------------------------------------------------------

    values = np.asarray(
        shap_values,
        dtype=float,
    )

    if (
        values.ndim
        == 2
    ):

        return values[
            :,
            :,
            None,
        ]

    if (
        values.ndim
        == 3
    ):

        return values

    raise ValueError(
        "Unsupported SHAP shape: "
        f"{values.shape}"
    )


# ======================================================================
# Mean absolute SHAP
# ======================================================================


def mean_absolute_shap(
    shap_values,
) -> np.ndarray:
    """
    Calculate mean absolute SHAP magnitude across samples.

    Returns
    -------
    ndarray
        Shape:
            n_features x n_outputs
    """

    values = standardize_shap_array(
        shap_values
    )

    return np.mean(
        np.abs(
            values
        ),
        axis=0,
    )


# ======================================================================
# Relative SHAP importance
# ======================================================================


def relative_mean_absolute_shap(
    shap_values,
) -> np.ndarray:
    """
    Express mean absolute SHAP values relative to the global maximum.

    Output scale:
        0-100

    Important
    ---------
    This is NOT a percentage contribution summing to 100%.

    It represents:

        Relative mean |SHAP| (% of maximum)

    This wording should be used in figure labels.
    """

    importance = (
        mean_absolute_shap(
            shap_values
        )
    )

    maximum = float(
        np.nanmax(
            importance
        )
    )

    if (
        maximum <= 0
        or not np.isfinite(
            maximum
        )
    ):

        return np.zeros_like(
            importance,
            dtype=float,
        )

    return (
        importance
        / maximum
        * 100.0
    )


# ======================================================================
# SHAP heatmap table
# ======================================================================


def shap_heatmap_table(
    shap_values,
    feature_names: Sequence[str],
    output_names: Sequence[str],
    *,
    relative: bool = True,
) -> pd.DataFrame:
    """
    Build feature x protein SHAP importance table.

    Parameters
    ----------
    shap_values
        SHAP values.

    feature_names
        Encoded model feature names.

    output_names
        Model protein/output names.

    relative
        If True, express importance relative to the global maximum.

    Returns
    -------
    pandas.DataFrame
        Rows = model features
        Columns = model outputs/proteins
    """

    values = (
        relative_mean_absolute_shap(
            shap_values
        )
        if relative
        else mean_absolute_shap(
            shap_values
        )
    )

    feature_names = list(
        feature_names
    )

    output_names = list(
        output_names
    )

    if (
        values.shape[0]
        != len(
            feature_names
        )
    ):

        raise ValueError(
            "Number of feature names does not match "
            "SHAP feature dimension."
        )

    if (
        values.shape[1]
        != len(
            output_names
        )
    ):

        raise ValueError(
            "Number of output names does not match "
            "SHAP output dimension."
        )

    return pd.DataFrame(
        values,
        index=feature_names,
        columns=output_names,
    )


# ======================================================================
# Global feature importance
# ======================================================================


def global_shap_feature_importance(
    shap_values,
    feature_names: Sequence[str],
    *,
    relative: bool = True,
) -> pd.DataFrame:
    """
    Summarize feature importance across all model outputs.

    For each feature:
        mean |SHAP| is averaged across outputs.

    The returned table is sorted from most to least important.
    """

    importance = (
        mean_absolute_shap(
            shap_values
        )
    )

    global_importance = np.mean(
        importance,
        axis=1,
    )

    feature_names = list(
        feature_names
    )

    if (
        len(
            feature_names
        )
        != len(
            global_importance
        )
    ):

        raise ValueError(
            "Number of feature names does not match "
            "SHAP feature dimension."
        )

    result = pd.DataFrame(
        {
            "feature":
                feature_names,

            "mean_abs_shap":
                global_importance,
        }
    )

    if relative:

        maximum = float(
            result[
                "mean_abs_shap"
            ].max()
        )

        if (
            maximum > 0
            and np.isfinite(
                maximum
            )
        ):

            result[
                "relative_mean_abs_shap"
            ] = (
                result[
                    "mean_abs_shap"
                ]
                / maximum
                * 100.0
            )

        else:

            result[
                "relative_mean_abs_shap"
            ] = 0.0

    result = result.sort_values(
        "mean_abs_shap",
        ascending=False,
    ).reset_index(
        drop=True
    )

    return result